### PR TITLE
UI Update. And important question

### PR DESCRIPTION
**Pull request by slstein14**
Are we still going to try and make this 2 player? I can start working
with that if we are.

### CODE REVIEW

**Comment by Alex-BusNet** [comment]
I'd say scrap 2 player. Can you set up the levels to include the walls and platform objects? I am still working on the collisions but most of them are there. Also, there is another merge conflict, can you hold off on up putting up a merge request till I fix it?

**Comment by slstein14** [comment]
Sure, I can hold up on the merges. Do you have something more current than what i'm using on the platforms? I dont think walls are even set up in what I'm working on.

**Comment by slstein14** [comment]
Sure, I can hold up on the merges. Do you have something more current than
what i'm using on the platforms? I dont think walls are even set up in what
I'm working on.

**Comment by Alex-BusNet** [comment]
yeah I do. I also made a lot of changes to the game physics and player actions. I am currently sorting them out.

**Comment by slstein14** [comment]
Ok, well, it would probably complicate things if I tried to add that to my current stuff if theres already merge issues. Ill try and write some loose code so I'm ready when i have the up to date code. The UI stuff in this set of patches is relatively unimportant stuff and I can do it again in about 5 minutes, so dont worry about that, and pretty much the only other thing I did was mess with player collisions, which you were also working on, so we can just ignore this set of merges.

**Comment by Alex-BusNet** [comment]
Alright. I'll see what I can include in the next set of merges.

**Comment by Alex-BusNet** [comment]
Okay, if you pull from the repo, and then make your changes, everything should be good

**Pull request closed without merging**
